# Generated by Django 2.2.3 on 2019-10-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=100, null=True, verbose_name='昵称'),
        ),
    ]
