# Generated by Django 2.2.3 on 2019-10-16 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20191013_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='abouts', to=settings.AUTH_USER_MODEL, verbose_name='用户本人'),
        ),
    ]
