# Generated by Django 2.2.3 on 2019-10-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191009_2036'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='view_num',
            field=models.PositiveIntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
